// Mock data for demonstration purposes
export const mockFeeds = [
  {
    id: "1",
    user_id: "demo-user",
    title: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    description: "Latest technology news and startup information",
    icon: "https://techcrunch.com/wp-content/uploads/2015/02/cropped-cropped-favicon-gradient.png",
    type: "rss",
    category_id: "1",
    last_fetched: "2025-07-29T10:00:00Z",
    created_at: "2025-07-20T10:00:00Z",
    updated_at: "2025-07-29T10:00:00Z",
  },
  {
    id: "2",
    user_id: "demo-user",
    title: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    description: "Technology, science, art, and culture",
    icon: "https://cdn.vox-cdn.com/uploads/chorus_asset/file/7395359/favicon-32x32.0.png",
    type: "rss",
    category_id: "1",
    last_fetched: "2025-07-29T09:30:00Z",
    created_at: "2025-07-21T10:00:00Z",
    updated_at: "2025-07-29T09:30:00Z",
  },
  {
    id: "3",
    user_id: "demo-user",
    title: "Marques Brownlee",
    url: "https://www.youtube.com/@mkbhd",
    description: "Tech reviews and gadget analysis",
    icon: "https://yt3.googleusercontent.com/ytc/AIf8zZQJhQxqJhQxqJhQxqJhQxqJhQxqJhQxqJhQxqJhQxq=s176-c-k-c0x00ffffff-no-rj",
    type: "youtube",
    category_id: "2",
    last_fetched: "2025-07-29T08:45:00Z",
    created_at: "2025-07-22T10:00:00Z",
    updated_at: "2025-07-29T08:45:00Z",
  },
  {
    id: "4",
    user_id: "demo-user",
    title: "Ars Technica",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    description: "Technology news and analysis",
    icon: "https://cdn.arstechnica.net/wp-content/uploads/2016/02/ars-logo-2016.png",
    type: "rss",
    category_id: "1",
    last_fetched: "2025-07-29T07:15:00Z",
    created_at: "2025-07-23T10:00:00Z",
    updated_at: "2025-07-29T07:15:00Z",
  },
  {
    id: "5",
    user_id: "demo-user",
    title: "Linus Tech Tips",
    url: "https://www.youtube.com/@LinusTechTips",
    description: "Computer hardware reviews and tech tips",
    icon: "https://yt3.googleusercontent.com/lkH37D712tiyphnu0Id0D5MwwQ7IRuwgQLVD05iMXlDpN3moO7NCHZjzL8I6uQbJ9uJhQxqJhQxq=s176-c-k-c0x00ffffff-no-rj",
    type: "youtube",
    category_id: "2",
    last_fetched: "2025-07-29T06:20:00Z",
    created_at: "2025-07-24T10:00:00Z",
    updated_at: "2025-07-29T06:20:00Z",
  },
];

export const mockCategories = [
  {
    id: "1",
    user_id: "demo-user",
    name: "Technology",
    color: "#3B82F6",
    icon: "💻",
    created_at: "2025-07-20T10:00:00Z",
    updated_at: "2025-07-20T10:00:00Z",
  },
  {
    id: "2",
    user_id: "demo-user",
    name: "YouTube",
    color: "#EF4444",
    icon: "📺",
    created_at: "2025-07-20T10:00:00Z",
    updated_at: "2025-07-20T10:00:00Z",
  },
  {
    id: "3",
    user_id: "demo-user",
    name: "News",
    color: "#10B981",
    icon: "📰",
    created_at: "2025-07-20T10:00:00Z",
    updated_at: "2025-07-20T10:00:00Z",
  },
];

export const mockRssItems = [
  {
    id: "rss-1",
    feed_id: "1",
    title: "Apple's New iPhone 16 Pro Features Revolutionary AI Capabilities",
    url: "https://techcrunch.com/2025/07/29/apple-iphone-16-pro-ai-features/",
    description:
      "Apple has unveiled the iPhone 16 Pro with groundbreaking AI features that will change how we interact with our phones.",
    thumbnail:
      "https://techcrunch.com/wp-content/uploads/2025/07/iphone-16-pro.jpg",
    content:
      "The new iPhone 16 Pro introduces advanced AI capabilities that allow users to...",
    author: "John Smith",
    published_at: "2025-07-29T10:00:00Z",
    guid: "techcrunch-iphone-16-pro-2025",
    language: "en",
    categories: ["Technology", "Apple", "AI"],
    created_at: "2025-07-29T10:00:00Z",
    feed_title: "TechCrunch",
  },
  {
    id: "rss-2",
    feed_id: "2",
    title: "The Future of Electric Vehicles: What's Next?",
    url: "https://www.theverge.com/2025/07/29/electric-vehicles-future-trends/",
    description:
      "Electric vehicles are evolving rapidly. Here's what we can expect in the next decade.",
    thumbnail:
      "https://cdn.vox-cdn.com/uploads/chorus_asset/file/2025/07/ev-future.jpg",
    content:
      "The electric vehicle market is experiencing unprecedented growth...",
    author: "Sarah Johnson",
    published_at: "2025-07-29T09:30:00Z",
    guid: "verge-ev-future-2025",
    language: "en",
    categories: ["Technology", "Electric Vehicles", "Future"],
    created_at: "2025-07-29T09:30:00Z",
    feed_title: "The Verge",
  },
  {
    id: "rss-3",
    feed_id: "4",
    title:
      "Quantum Computing Breakthrough: New Algorithm Solves Complex Problems",
    url: "https://arstechnica.com/2025/07/quantum-computing-breakthrough/",
    description:
      "Researchers have developed a new quantum algorithm that can solve previously unsolvable problems.",
    thumbnail:
      "https://cdn.arstechnica.net/wp-content/uploads/2025/07/quantum-computing.jpg",
    content:
      "A team of researchers has made a significant breakthrough in quantum computing...",
    author: "Dr. Michael Chen",
    published_at: "2025-07-29T07:15:00Z",
    guid: "arstechnica-quantum-2025",
    language: "en",
    categories: ["Technology", "Quantum Computing", "Research"],
    created_at: "2025-07-29T07:15:00Z",
    feed_title: "Ars Technica",
  },
];

export const mockYoutubeItems = [
  {
    id: "yt-1",
    feed_id: "3",
    video_id: "dQw4w9WgXcQ",
    title: "iPhone 16 Pro Review: Is It Worth the Upgrade?",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    description:
      "In this comprehensive review, I test all the new features of the iPhone 16 Pro and help you decide if it's worth upgrading.",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    channel_title: "Marques Brownlee",
    published_at: "2025-07-29T08:45:00Z",
    duration: "15:30",
    view_count: 1250000,
    like_count: 45000,
    comment_count: 3200,
    is_short: false,
    created_at: "2025-07-29T08:45:00Z",
    feed_title: "Marques Brownlee",
  },
  {
    id: "yt-2",
    feed_id: "5",
    video_id: "jNQXAC9IVRw",
    title: "Building the Ultimate Gaming PC in 2025",
    url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
    description:
      "We build the most powerful gaming PC possible with the latest hardware and show you how to do it yourself.",
    thumbnail: "https://i.ytimg.com/vi/jNQXAC9IVRw/maxresdefault.jpg",
    channel_title: "Linus Tech Tips",
    published_at: "2025-07-29T06:20:00Z",
    duration: "22:15",
    view_count: 890000,
    like_count: 32000,
    comment_count: 2100,
    is_short: false,
    created_at: "2025-07-29T06:20:00Z",
    feed_title: "Linus Tech Tips",
  },
];

export const mockUserInteractions = [
  {
    id: "int-1",
    user_id: "demo-user",
    item_id: "rss-1",
    item_type: "rss",
    is_read: true,
    is_favorite: true,
    is_read_later: false,
    read_progress: 100,
    read_at: "2025-07-29T10:30:00Z",
    created_at: "2025-07-29T10:00:00Z",
    updated_at: "2025-07-29T10:30:00Z",
  },
  {
    id: "int-2",
    user_id: "demo-user",
    item_id: "rss-2",
    item_type: "rss",
    is_read: false,
    is_favorite: false,
    is_read_later: true,
    read_progress: 0,
    read_at: null,
    created_at: "2025-07-29T09:30:00Z",
    updated_at: "2025-07-29T09:30:00Z",
  },
  {
    id: "int-3",
    user_id: "demo-user",
    item_id: "yt-1",
    item_type: "youtube",
    is_read: true,
    is_favorite: false,
    is_read_later: false,
    read_progress: 100,
    read_at: "2025-07-29T09:00:00Z",
    created_at: "2025-07-29T08:45:00Z",
    updated_at: "2025-07-29T09:00:00Z",
  },
];

// Combine and format items for display
export const mockRecentItems = [
  {
    id: "rss-1",
    title: "Apple's New iPhone 16 Pro Features Revolutionary AI Capabilities",
    description:
      "Apple has unveiled the iPhone 16 Pro with groundbreaking AI features that will change how we interact with our phones.",
    published_at: "2025-07-29T10:00:00Z",
    feed_id: "1",
    feed_title: "TechCrunch",
    type: "rss",
    url: "https://techcrunch.com/2025/07/29/apple-iphone-16-pro-ai-features/",
    thumbnail:
      "https://techcrunch.com/wp-content/uploads/2025/07/iphone-16-pro.jpg",
    is_read: true,
    is_favorite: true,
    is_read_later: false,
  },
  {
    id: "yt-1",
    title: "iPhone 16 Pro Review: Is It Worth the Upgrade?",
    description:
      "In this comprehensive review, I test all the new features of the iPhone 16 Pro and help you decide if it's worth upgrading.",
    published_at: "2025-07-29T08:45:00Z",
    feed_id: "3",
    feed_title: "Marques Brownlee",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    is_read: true,
    is_favorite: false,
    is_read_later: false,
  },
  {
    id: "rss-2",
    title: "The Future of Electric Vehicles: What's Next?",
    description:
      "Electric vehicles are evolving rapidly. Here's what we can expect in the next decade.",
    published_at: "2025-07-29T09:30:00Z",
    feed_id: "2",
    feed_title: "The Verge",
    type: "rss",
    url: "https://www.theverge.com/2025/07/29/electric-vehicles-future-trends/",
    thumbnail:
      "https://cdn.vox-cdn.com/uploads/chorus_asset/file/2025/07/ev-future.jpg",
    is_read: false,
    is_favorite: false,
    is_read_later: true,
  },
  {
    id: "yt-2",
    title: "Building the Ultimate Gaming PC in 2025",
    description:
      "We build the most powerful gaming PC possible with the latest hardware and show you how to do it yourself.",
    published_at: "2025-07-29T06:20:00Z",
    feed_id: "5",
    feed_title: "Linus Tech Tips",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
    thumbnail: "https://i.ytimg.com/vi/jNQXAC9IVRw/maxresdefault.jpg",
    is_read: false,
    is_favorite: false,
    is_read_later: false,
  },
  {
    id: "rss-3",
    title:
      "Quantum Computing Breakthrough: New Algorithm Solves Complex Problems",
    description:
      "Researchers have developed a new quantum algorithm that can solve previously unsolvable problems.",
    published_at: "2025-07-29T07:15:00Z",
    feed_id: "4",
    feed_title: "Ars Technica",
    type: "rss",
    url: "https://arstechnica.com/2025/07/quantum-computing-breakthrough/",
    thumbnail:
      "https://cdn.arstechnica.net/wp-content/uploads/2025/07/quantum-computing.jpg",
    is_read: false,
    is_favorite: false,
    is_read_later: false,
  },
];

export const mockStats = {
  feeds: mockFeeds.length,
  favorites: mockUserInteractions.filter((i) => i.is_favorite).length,
  readLater: mockUserInteractions.filter((i) => i.is_read_later).length,
  unread: mockRecentItems.filter((item) => !item.is_read).length,
};

export const mockUser = {
  id: "demo-user",
  email: "demo@feedtune.com",
  email_confirmed_at: "2025-07-20T10:00:00Z",
  aud: "authenticated",
  role: "authenticated",
  display_name: "Demo User",
  avatar_url: null,
  created_at: "2025-07-20T10:00:00Z",
  updated_at: "2025-07-20T10:00:00Z",
  preferences: {
    theme: "system",
    language: "en",
    autoSync: true,
    notifications: true,
  },
};
